version: "3.8"

services:
  localstack:
    image: localstack/localstack:1.0.0
    ports:
      - "4566:4566"
    environment:
      SQS_ENDPOINT_STRATEGY: path
      SERVICES: sqs
    volumes: 
      - ./volume:/var/lib/localstack