version: "3.9"

services:
  backend:
    container_name: amazonlinux2-compose-container
    build: .
    tty: true
    platform: linux/x86_64
  localstack:
    image: localstack/localstack
    ports:
      - "14566:4566"
    environment:
      - SERVICES=${SERCICES-sqs,sns,s3}