version: "3.9"

services:
  backend:
    container_name: amazonlinux2-compose-container
    build: .
    tty: true
    platform: linux/x86_64
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=${SERCICES-sqs,sns,s3}
      - DATA_DIR=/tmp/localstack/data
    volumes: 
      - ./localstack:/tmp/localstack