version: "3.9"

services:
  backend:
    container_name: amazonlinux2-compose-container
    build: .
    tty: true
    platform: linux/x86_64
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=ap-northeast-1
    volumes: 
      - ./localstack:/tmp/localstack