version: "3.9"

services:
  backend:
    container_name: amazonlinux2-compose-container
    build: .
    tty: true
    platform: linux/x86_64
  localstack:
    image: localstack/localstack:1.0.0
    ports:
      - "4566:4566"
    environment:
      SQS_ENDPOINT_STRATEGY: path
    volumes: 
      - ./localstack:/var/lib/localstack