version: 2.1
orbs:
  localstack: localstack/platform@1.0

commands:
  setup:
    steps:
      - run:
          command: sudo apt-get update && sudo apt install python3-pip && sudo pip3 install awscli

#executors:
#  default:
#    machine: cimg/go:1.18
#  container:
#    docker: localstack/default
jobs:
  run-localstack-setup:
    docker:
      - image: cimg/go:1.18
      - image: localstack/localstack:1.0.0
    steps:
      - run:
          command: awslocal sqs create-queue --queue-name prepared --region=ap-northeast-1
      - run:
          command: aws sqs list-queues --endpoint-url http://localhost:4566 --region ap-northeast-1
      - run:
          command: echo "queue list"
  run-test:
    docker:
      - image: cimg/go:1.18
        auth:
          username: umibows
          password: $DOCKERHUB_PASSWORD
      - image: localstack/localstack:1.0.0
        auth:
          username: umibows
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup
#      - run:
#          command: docker-compose -f docker-compose.yml up
      - run:
          command: aws sqs create-queue --queue-name prepared3 --region ap-northeast-1 --endpoint http://localhost:4566
      - run:
          command: aws sqs list-queues --endpoint-url http://localhost:4566 --region ap-northeast-1
      - run:
          command: go test ./src/main/... -v
workflows:
#  integration-setup:
#    jobs:
#      - run-localstack-setup
  integration-test:
    jobs:
      - run-test