version: 2.1
orbs:
  localstack: localstack/platform@1.0
jobs:
  run-localstack-setup:
    executor: localstack/default
    steps:
      - localstack/startup
      - run:
          command: awslocal sqs create-queue --queue-name prepared
      - run:
          command: awslocal sqs get-queue-attributes --attribute-names All --queue-url=prepared
      - run:
          command: echo "queue list"
  run-test:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run:
          command: go test ./src/main/... -v
workflows:
  integration-setup:
    jobs:
      - run-localstack-setup
  integration-test:
    jobs:
      - run-test