version: 2.1
jobs:
  build:
    docker:
      - image: localstack/localstack
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: localstack/localstack
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test