version: 2.1
parameters:
  deploy_type:
    type: string
    default: ""
jobs:
  run-test:
    docker:
      - image: cimg/go:1.18
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: localstack/localstack:1.0.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          command: echo "<< pipeline.parameters.deploy_type >>"
      - run:
          command: sudo apt-get update && sudo apt install python3-pip && sudo pip3 install awscli
      - run:
          command: aws sqs create-queue --queue-name prepared --region ap-northeast-1 --endpoint http://localhost:4566
      - run:
          command: go test ./src/main/... -v
      - run:
          command: |
            echo test
            TEST=aaa
            echo $TEST
workflows:
  integration-test:
    jobs:
      - run-test